version: '3'

services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_USER: ${USER:-app}
        APP_UID: ${UID:-1000}
    command: ['foreman', 'start']
    ports: ['3000:3000', '3035:3035']
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      DATABASE_HOST: postgres
      RAILS_LOG_TO_STDOUT: 'true'
    volumes:
      - .:/app
      - bundle:/data/bundle
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

volumes:
  db:
  bundle:
  redis:
